# fly.toml app configuration file generated for askipcc on 2023-06-06T00:35:20+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "askipcc"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[env]
REDIS_URL = "redis://default:0fb128ce7e054d7891dd887d3d6c53e9@fly-aged-breeze-7788.upstash.io"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"